name: Primer Pipeline CI

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:

  hello-ci:
    name: Hello CI
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mostrar información del entorno
        run: |
          echo "================================"
          echo "      PRIMER PIPELINE CI"
          echo "================================"
          echo "Repositorio: ${{ github.repository }}"
          echo "Rama: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "================================"

      - name: Mostrar fecha y hora
        run: date

      - name: Mostrar versión de Git
        run: git --version

      - name: Finalizar pipeline
        run: echo "Pipeline inicial ejecutado correctamente."


  build:
    name: Build
    needs: hello-ci
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests


  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Finalizar pruebas
        run: echo "Pruebas unitarias ejecutadas correctamente."